[package]
name = "projektwahl-wasm"
version = "0.1.0"
authors = ["Moritz Hedtke <Moritz.Hedtke@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
